"""empty message

Revision ID: 616acbe54fa5
Revises: c62ee295ceb9
Create Date: 2018-11-08 17:06:30.849744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616acbe54fa5'
down_revision = 'c62ee295ceb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('average_inference_time', sa.Float(), nullable=True))
    op.add_column('job', sa.Column('total_job_time', sa.Float(), nullable=True))
    op.create_index(op.f('ix_job_celery_id'), 'job', ['celery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_celery_id'), table_name='job')
    op.drop_column('job', 'total_job_time')
    op.drop_column('job', 'average_inference_time')
    # ### end Alembic commands ###
