"""empty message

Revision ID: 74a2ed9e56a0
Revises: 
Create Date: 2018-10-30 16:35:42.240293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a2ed9e56a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frame_position'), 'frame', ['position'], unique=False)
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('y_min', sa.Float(), nullable=True),
    sa.Column('x_min', sa.Float(), nullable=True),
    sa.Column('y_max', sa.Float(), nullable=True),
    sa.Column('x_max', sa.Float(), nullable=True),
    sa.Column('object_name', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection')
    op.drop_index(op.f('ix_frame_position'), table_name='frame')
    op.drop_table('frame')
    op.drop_table('video')
    # ### end Alembic commands ###
