"""empty message

Revision ID: c62ee295ceb9
Revises: 74a2ed9e56a0
Create Date: 2018-10-31 12:52:14.806537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62ee295ceb9'
down_revision = '74a2ed9e56a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=32), nullable=True),
    sa.Column('celery_id', sa.String(length=48), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_video_id'), 'job', ['video_id'], unique=False)
    op.create_index(op.f('ix_detection_frame_id'), 'detection', ['frame_id'], unique=False)
    op.create_index(op.f('ix_frame_video_id'), 'frame', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frame_video_id'), table_name='frame')
    op.drop_index(op.f('ix_detection_frame_id'), table_name='detection')
    op.drop_index(op.f('ix_job_video_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
